version: "3"
services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    tty: true
    volumes:
      - ./app:/tmp/app
      - ./view/dist:/tmp/public
    extra_hosts:
      - "local_dev:${LOCAL_HOST}"
    ports:
      - "5000:5000"
  node_js:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./view:/tmp
    extra_hosts:
      - "local_js:${LOCAL_HOST}"
    ports:
      - "10080:8080"
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - TZ='Asia/Tokyo'