version: "3"
services:
  python:
    build:
      context: .
      dockerfile: ./Docker/python/Dockerfile
    tty: true
    volumes:
      - ./app:/tmp/app
    extra_hosts:
      - "local_dev:192.168.11.8"
    ports:
      - "5000:5000"
  mysql:
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/conf.d:/etc/mysql/conf.d/temp
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - TZ='Asia/Tokyo'